import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Home/Navbar";
import Hero from "@/components/Home/Hero";
import LocationComponent from "@/components/Common/LocationComponent";
import Features from "@/components/Home/Features";
import Banners from "@/components/Home/Banners";
import Testimonials from "@/components/Home/Testimonials";
import InstagramPhotos from "@/components/Home/FollowOnInstagram";
import Footer from "@/components/Common/Footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <LocationComponent />
        <Navbar />
        <Hero />
        <Features />
        <Banners />
        <Testimonials />
        <InstagramPhotos />
        <Footer />
      </body>
    </html>
  );
}
